DROP SCHEMA IF EXISTS Banco;
CREATE SCHEMA Banco;

USE Banco;
CREATE TABLE CLIENTES (
	Ci VARCHAR(8) PRIMARY KEY,
    Nombre VARCHAR(20) NOT NULL,
    Apellido VARCHAR(20) NOT NULL
);

CREATE TABLE MONEDAS (
	MonedaId VARCHAR(3) PRIMARY KEY,
    descripcion VARCHAR(8) NOT NULL
);

CREATE TABLE CUENTAS (
	Ci VARCHAR(8),
    NumeroDeCuenta VARCHAR(12),
    Moneda VARCHAR(3) NOT NULL,
    Saldo DECIMAL(18, 2) NOT NULL,
    FechaApertura DATETIME NOT NULL,
    PRIMARY KEY CUENTAS(CI, NumeroDeCuenta),
    FOREIGN KEY (Moneda) REFERENCES MONEDAS(MonedaId)
);

/* -- Auditoria transaccional
CREATE TABLE AUDITORIA (
	Id INT AUTO_INCREMENT PRIMARY KEY,
    Ci VARCHAR(8) NOT NULL,
    NumeroDeCuenta VARCHAR(12) NOT NULL,
    Fecha DATETIME NOT NULL,
    FOREIGN KEY (Ci, NumeroDeCuenta) REFERENCES CUENTAS(Ci, NumeroDeCuenta)
);
*/

CREATE TABLE AUDITORIA (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Ci VARCHAR(8),
    NumeroDeCuenta VARCHAR(12),
    Fecha DATETIME DEFAULT NOW()
) ENGINE = MyISAM;

CREATE TABLE OPERACIONES (
	Tipo INT PRIMARY KEY,
    Descripcion VARCHAR(50) NOT NULL
);

CREATE TABLE MOVIMIENTOS(
	IdMovimiento INT AUTO_INCREMENT PRIMARY KEY,
    Ci VARCHAR(8) NOT NULL,
    NumeroDeCuenta VARCHAR(12) NOT NULL,
    Tipo INT NOT NULL,
    Monto DECIMAL(18, 2) NOT NULL,
    Fecha DATETIME NOT NULL,
    Ref INT,
    FOREIGN KEY (Ci, NumeroDeCuenta) REFERENCES CUENTAS(Ci, NumeroDeCuenta),
    FOREIGN KEY (Tipo) REFERENCES OPERACIONES(Tipo)
);

CREATE TABLE CUENTA_MONEDA (
	MonedaId VARCHAR(3),
	Ci VARCHAR(8),
    NumeroDeCuenta VARCHAR(12),
    PRIMARY KEY (MonedaId, Ci, NumeroDeCuenta),
    FOREIGN KEY (MonedaId) REFERENCES MONEDAS(MonedaId),
    FOREIGN KEY (Ci, NumeroDeCuenta) REFERENCES CUENTAS(Ci, NumeroDeCuenta)
);

CREATE TABLE SALDOS_CLIENTE_MONEDA(
	Ci VARCHAR(8),
	MonedaId VARCHAR(3),
	SaldoTotal DECIMAL(18, 2) NOT NULL,
    PRIMARY KEY (Ci, MonedaId),
	FOREIGN KEY (MonedaId) REFERENCES MONEDAS(MonedaId),
    FOREIGN KEY (Ci) REFERENCES CLIENTES(Ci)
);